### ISSUE TITLE
Device index must not be negative

### ISSUE THREAD

**Issue by q-learning-trader** [junwoopark92/Self-Supervised-Contrastive-Forecsating#1]
Very nice work, congratulations!
I am still reading your paper and in the mean time test and studying the software.
I believe there is a bug in the loss:

```
# python run.py --AutoCon --AutoCon_multiscales 720 --AutoCon_wnorm LastVal --AutoCon_lambda 0.1 --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24 --model AutoConNet --data ETTh2 --seq_len 336 --pred_len 720 --enc_in 1 --des 'Exp' --itr 1 --batch_size 64 --learning_rate 0.005 --feature S
Args in experiment:
Namespace(AutoCon=True, AutoCon_lambda=0.1, AutoCon_multiscales=[720], AutoCon_wnorm='LastVal', activation='gelu', anomaly_ratio=0.25, batch_size=64, c_out=1, checkpoints='./checkpoints/', d_ff=16, d_layers=1, d_model=16, data='ETTh2', data_path='ETTh2.csv', dec_in=7, des='Exp', devices='0,1,2,3', distil=True, dropout=0.1, e_layers=3, embed='timeF', enc_in=1, factor=1, features='S', freq='h', gpu=0, is_training=1, itr=1, label_len=48, learning_rate=0.005, loss='MSE', lradj='type1', mask_rate=0.25, model='AutoConNet', model_id='ICLR24', moving_avg=25, n_heads=8, num_kernels=6, num_workers=2, output_attention=False, p_hidden_dims=[128, 128], p_hidden_layers=2, patience=3, pred_len=720, root_path='./dataset/ETT-small', save=False, seasonal_patterns='Monthly', seq_len=336, target='OT', task_name='long_term_forecast', top_k=5, train_epochs=10, train_ratio=0.6, use_amp=False, use_gpu=False, use_multi_gpu=False)
Use CPU
TimeFeatureEmbedding-wo-freq:   []
model parameters:492225
train 7585
Auto-correlation values(abs):[1.        0.9999075] ~ [1.77736511e-04 8.89139511e-05]
Autocorrelation calculation time: 0.0827
>>>>>>>start training : long_term_forecast_ICLR24_AutoConNet_ETTh2_ftS_sl336_ll48_pl720_dm16_nh8_el3_dl1_df16_fc1_ebtimeF_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 7585
val 2161
test 2161
Traceback (most recent call last):
  File "run.py", line 162, in <module>
    exp.train(setting)
  File "Self-Supervised-Contrastive-Forecsating/exp/exp_long_term_forecasting_with_AutoCon.py", line 167, in train
    local_loss, global_loss = self.AutoCon_loss(features, global_pos_labels)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "Self-Supervised-Contrastive-Forecsating/layers/losses.py", line 204, in forward
    feature_idxs = torch.rand(B, self.seq_len).argsort(-1)[:, :self.seq_len//3].to(features.get_device())
RuntimeError: Device index must not be negative
```

Software version seems to be correct:

```
# python3 -V
Python 3.8.10
# pip3 list | egrep -i 'torch|numpy|pandas|statsmodel'
numpy                             1.23.5
pandas                            1.5.2
pytorch-quantization              2.1.2
statsmodels                       0.14.1
torch                             1.7.1
torch-tensorrt                    1.4.0.dev0
torchtext                         0.13.0a0+fae8e8c
torchvision                       0.15.0a0
```

Do you have an idea what is wrong?

**Comment by q-learning-trader** [comment]
Sorry my docker container was not properly setup for using GPU.
